# Generated by Django 2.2.19 on 2023-06-04 13:13

import re

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тег рецепта', max_length=200, unique=True, verbose_name='Тег')),
                ('color', models.CharField(help_text='Цвет тега', max_length=7, unique=True, validators=[core.validators.hex_validator], verbose_name='Цвет')),
                ('slug', models.CharField(help_text='Слаг тега', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Слаг')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
