# Generated by Django 3.2.19 on 2023-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230604_0619'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='%(app_label)s_%(class)s_user_author_unique',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='users_subscription_user_author_unique'),
        ),
    ]
